//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroSim.DataSource.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroSim.DataSource.Entities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitás kezdőéve.
        /// </summary>
        public static string ActiveYear {
            get {
                return ResourceManager.GetString("ActiveYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Életkor.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alap.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyermekek száma.
        /// </summary>
        public static string BirthOrder {
            get {
                return ResourceManager.GetString("BirthOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. gyerek.
        /// </summary>
        public static string BirthOrderLabel {
            get {
                return ResourceManager.GetString("BirthOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. vagy későbbi gyerek.
        /// </summary>
        public static string BirthOrderMoreLabel {
            get {
                return ResourceManager.GetString("BirthOrderMoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születési év.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyermek végzettsége.
        /// </summary>
        public static string ChildEducation {
            get {
                return ResourceManager.GetString("ChildEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettség típus.
        /// </summary>
        public static string DetEducationType {
            get {
                return ResourceManager.GetString("DetEducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születések.
        /// </summary>
        public static string DsBirth {
            get {
                return ResourceManager.GetString("DsBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születések részletezve.
        /// </summary>
        public static string DsBirthComplete {
            get {
                return ResourceManager.GetString("DsBirthComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születések végzettségenként.
        /// </summary>
        public static string DsBirthEdu {
            get {
                return ResourceManager.GetString("DsBirthEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozások.
        /// </summary>
        public static string DsDeath {
            get {
                return ResourceManager.GetString("DsDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozások végzettségenként.
        /// </summary>
        public static string DsDeathEdu {
            get {
                return ResourceManager.GetString("DsDeathEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinisztikus végzettség.
        /// </summary>
        public static string DsDetEdu {
            get {
                return ResourceManager.GetString("DsDetEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűségek.
        /// </summary>
        public static string DsFertility {
            get {
                return ResourceManager.GetString("DsFertility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozási valószínűség.
        /// </summary>
        public static string DsMortality {
            get {
                return ResourceManager.GetString("DsMortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb.
        /// </summary>
        public static string DsOther {
            get {
                return ResourceManager.GetString("DsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimenet.
        /// </summary>
        public static string DsOutput {
            get {
                return ResourceManager.GetString("DsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születés korfa.
        /// </summary>
        public static string DspBirthAgeTree {
            get {
                return ResourceManager.GetString("DspBirthAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születés számok.
        /// </summary>
        public static string DspBirthBase {
            get {
                return ResourceManager.GetString("DspBirthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születés számok részletezve.
        /// </summary>
        public static string DspBirthComplete {
            get {
                return ResourceManager.GetString("DspBirthComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Születés korfa részletezve.
        /// </summary>
        public static string DspBirthCompleteAgeTree {
            get {
                return ResourceManager.GetString("DspBirthCompleteAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers születés számok részletezve.
        /// </summary>
        public static string DspBirthCompleteRaw {
            get {
                return ResourceManager.GetString("DspBirthCompleteRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt születés korfa végzettségek szerint.
        /// </summary>
        public static string DspBirthEduAgeTree {
            get {
                return ResourceManager.GetString("DspBirthEduAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt születés számok végzettségek szerint.
        /// </summary>
        public static string DspBirthEduBase {
            get {
                return ResourceManager.GetString("DspBirthEduBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers születés számok végzettségek szerint.
        /// </summary>
        public static string DspBirthEduRaw {
            get {
                return ResourceManager.GetString("DspBirthEduRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülőképes nők adatok részletezve.
        /// </summary>
        public static string DspBirthMother {
            get {
                return ResourceManager.GetString("DspBirthMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülőképes nők korfa részletezve.
        /// </summary>
        public static string DspBirthMotherAgeTree {
            get {
                return ResourceManager.GetString("DspBirthMotherAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers szülőképes nők adatok részletezve.
        /// </summary>
        public static string DspBirthMotherRaw {
            get {
                return ResourceManager.GetString("DspBirthMotherRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers születés számok.
        /// </summary>
        public static string DspBirthRaw {
            get {
                return ResourceManager.GetString("DspBirthRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozás korfa.
        /// </summary>
        public static string DspDeathAgeTree {
            get {
                return ResourceManager.GetString("DspDeathAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers halálozás számok.
        /// </summary>
        public static string DspDeathBase {
            get {
                return ResourceManager.GetString("DspDeathBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt halálozás korfa végzettségek szerint.
        /// </summary>
        public static string DspDeathEduAgeTree {
            get {
                return ResourceManager.GetString("DspDeathEduAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt halálozás számok végzettségek szerint.
        /// </summary>
        public static string DspDeathEduBase {
            get {
                return ResourceManager.GetString("DspDeathEduBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigált halálozási számok népesség szerint.
        /// </summary>
        public static string DspDeathEduExt {
            get {
                return ResourceManager.GetString("DspDeathEduExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigált halálozási korfa népesség szerint.
        /// </summary>
        public static string DspDeathEduExtAgeTree {
            get {
                return ResourceManager.GetString("DspDeathEduExtAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers halálozás számok végzettségek szerint.
        /// </summary>
        public static string DspDeathEduRaw {
            get {
                return ResourceManager.GetString("DspDeathEduRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozás számok.
        /// </summary>
        public static string DspDeathRaw {
            get {
                return ResourceManager.GetString("DspDeathRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinisztikus végzettség valószínűségek.
        /// </summary>
        public static string DspDetEdu {
            get {
                return ResourceManager.GetString("DspDetEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers determinisztikus végzettség valószínűségek.
        /// </summary>
        public static string DspDetEduRaw {
            get {
                return ResourceManager.GetString("DspDetEduRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazdasági növekedés.
        /// </summary>
        public static string DspEconomicGrowth {
            get {
                return ResourceManager.GetString("DspEconomicGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettségfüggő alapváltozók.
        /// </summary>
        public static string DspEduBasedVar {
            get {
                return ResourceManager.GetString("DspEduBasedVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűségek korfa részletezve.
        /// </summary>
        public static string DspFertilityAgeTree {
            get {
                return ResourceManager.GetString("DspFertilityAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűségek részletezve.
        /// </summary>
        public static string DspFertilityBase {
            get {
                return ResourceManager.GetString("DspFertilityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűségek előrejelzés részletezve.
        /// </summary>
        public static string DspFertilityForecast {
            get {
                return ResourceManager.GetString("DspFertilityForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűségek előrejelzés korfa részletezve.
        /// </summary>
        public static string DspFertilityForecastAgeTree {
            get {
                return ResourceManager.GetString("DspFertilityForecastAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűség szorzók részletezve.
        /// </summary>
        public static string DspFertilityMultiplier {
            get {
                return ResourceManager.GetString("DspFertilityMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülési valószínűség szorzók korfa részletezve.
        /// </summary>
        public static string DspFertilityMultiplierAgeTree {
            get {
                return ResourceManager.GetString("DspFertilityMultiplierAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers szülési valószínűségek részletezve.
        /// </summary>
        public static string DspFertilityRaw {
            get {
                return ResourceManager.GetString("DspFertilityRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers szülési valószínűségek korfa részletezve.
        /// </summary>
        public static string DspFertilityRawAgeTree {
            get {
                return ResourceManager.GetString("DspFertilityRawAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevándorló eloszlások.
        /// </summary>
        public static string DspImmigrantSettings {
            get {
                return ResourceManager.GetString("DspImmigrantSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jövedelem növekedés.
        /// </summary>
        public static string DspIncomeIncrease {
            get {
                return ResourceManager.GetString("DspIncomeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jövedelem növekedés ábrák.
        /// </summary>
        public static string DspIncomeIncreaseGraphs {
            get {
                return ResourceManager.GetString("DspIncomeIncreaseGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisebbségi arányok.
        /// </summary>
        public static string DspMinorityRates {
            get {
                return ResourceManager.GetString("DspMinorityRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozási valószínűség korfa végzettség szerint.
        /// </summary>
        public static string DspMortalityEduAgeTree {
            get {
                return ResourceManager.GetString("DspMortalityEduAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozási valószínűség végzettség szerint.
        /// </summary>
        public static string DspMortalityEduBase {
            get {
                return ResourceManager.GetString("DspMortalityEduBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozási valószínűség előrejelzés végzettség szerint.
        /// </summary>
        public static string DspMortalityEduForecast {
            get {
                return ResourceManager.GetString("DspMortalityEduForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halálozási valószínűség korfa előrejelzés végzettség szerint.
        /// </summary>
        public static string DspMortalityEduForecastAgeTree {
            get {
                return ResourceManager.GetString("DspMortalityEduForecastAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettségek szerinti halálozás valószínűség szorzók korfa.
        /// </summary>
        public static string DspMortalityEduMultiplierAgeTree {
            get {
                return ResourceManager.GetString("DspMortalityEduMultiplierAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettségek szerinti halálozás valószínűség szorzók.
        /// </summary>
        public static string DspMortalityEduMultipliers {
            get {
                return ResourceManager.GetString("DspMortalityEduMultipliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers halálozási valószínűség végzettség szerint.
        /// </summary>
        public static string DspMortalityEduRaw {
            get {
                return ResourceManager.GetString("DspMortalityEduRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers halálozási valószínűség korfa végzettség szerint.
        /// </summary>
        public static string DspMortalityEduRawAgeTree {
            get {
                return ResourceManager.GetString("DspMortalityEduRawAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Népesség.
        /// </summary>
        public static string DsPopulation {
            get {
                return ResourceManager.GetString("DsPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Népesség végzettségenként.
        /// </summary>
        public static string DsPopulationEdu {
            get {
                return ResourceManager.GetString("DsPopulationEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazdasági növekedés.
        /// </summary>
        public static string DspOutputEconomicGrowth {
            get {
                return ResourceManager.GetString("DspOutputEconomicGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettség valószínűség.
        /// </summary>
        public static string DspOutputEducation {
            get {
                return ResourceManager.GetString("DspOutputEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilitás.
        /// </summary>
        public static string DspOutputFertility {
            get {
                return ResourceManager.GetString("DspOutputFertility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilitás teljes.
        /// </summary>
        public static string DspOutputFertilityTotal {
            get {
                return ResourceManager.GetString("DspOutputFertilityTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jövedelem növekedés.
        /// </summary>
        public static string DspOutputIncomeIncrease {
            get {
                return ResourceManager.GetString("DspOutputIncomeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortalitás.
        /// </summary>
        public static string DspOutputMortality {
            get {
                return ResourceManager.GetString("DspOutputMortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíjtípus alapértéke.
        /// </summary>
        public static string DspOutputPensionBase {
            get {
                return ResourceManager.GetString("DspOutputPensionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíj szorzók.
        /// </summary>
        public static string DspOutputPensionMultiplier {
            get {
                return ResourceManager.GetString("DspOutputPensionMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíjtípus alapszorzója.
        /// </summary>
        public static string DspOutputPensionTheta {
            get {
                return ResourceManager.GetString("DspOutputPensionTheta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induló népesség.
        /// </summary>
        public static string DspOutputPopulation {
            get {
                return ResourceManager.GetString("DspOutputPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validáló induló népesség.
        /// </summary>
        public static string DspOutputPopulationValidation {
            get {
                return ResourceManager.GetString("DspOutputPopulationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Társadalmi csoport végzettség típusa.
        /// </summary>
        public static string DspOutputSocialGroupEducationType {
            get {
                return ResourceManager.GetString("DspOutputSocialGroupEducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induló jövedelem.
        /// </summary>
        public static string DspOutputStartingIncome {
            get {
                return ResourceManager.GetString("DspOutputStartingIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkavállalói státusz átmenet.
        /// </summary>
        public static string DspOutputWorkStatus {
            get {
                return ResourceManager.GetString("DspOutputWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkavállalói státusz ideje Max.
        /// </summary>
        public static string DspOutputWorkStatusMaxTime {
            get {
                return ResourceManager.GetString("DspOutputWorkStatusMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkavállalói státusz ideje Min.
        /// </summary>
        public static string DspOutputWorkStatusMinTime {
            get {
                return ResourceManager.GetString("DspOutputWorkStatusMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkaviszony kezdete.
        /// </summary>
        public static string DspOutputWorkYearStart {
            get {
                return ResourceManager.GetString("DspOutputWorkYearStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíjtípustól függő alapváltozók.
        /// </summary>
        public static string DspPensionBasedVar {
            get {
                return ResourceManager.GetString("DspPensionBasedVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíj szorzók.
        /// </summary>
        public static string DspPensionMultiplier {
            get {
                return ResourceManager.GetString("DspPensionMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt népesség korfa.
        /// </summary>
        public static string DspPopulationAgeTree {
            get {
                return ResourceManager.GetString("DspPopulationAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt népesség adatok.
        /// </summary>
        public static string DspPopulationBase {
            get {
                return ResourceManager.GetString("DspPopulationBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Népesség korfa végzettség szerint.
        /// </summary>
        public static string DspPopulationEduAgeTree {
            get {
                return ResourceManager.GetString("DspPopulationEduAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrt népesség adatok végzettség szerint.
        /// </summary>
        public static string DspPopulationEduBase {
            get {
                return ResourceManager.GetString("DspPopulationEduBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers népesség adatok végzettség szerint.
        /// </summary>
        public static string DspPopulationEduRaw {
            get {
                return ResourceManager.GetString("DspPopulationEduRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Népesség adatok végzettség szerint.
        /// </summary>
        public static string DspPopulationEduYearly {
            get {
                return ResourceManager.GetString("DspPopulationEduYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigált népesség adatok.
        /// </summary>
        public static string DspPopulationExt {
            get {
                return ResourceManager.GetString("DspPopulationExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigált népesség korfa.
        /// </summary>
        public static string DspPopulationExtAgeTree {
            get {
                return ResourceManager.GetString("DspPopulationExtAgeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers népesség adatok.
        /// </summary>
        public static string DspPopulationRaw {
            get {
                return ResourceManager.GetString("DspPopulationRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Társadalmi csoport végzettség típusa.
        /// </summary>
        public static string DspSocialGroupEducationType {
            get {
                return ResourceManager.GetString("DspSocialGroupEducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes induló népesség.
        /// </summary>
        public static string DspStartComplete {
            get {
                return ResourceManager.GetString("DspStartComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers induló népesség.
        /// </summary>
        public static string DspStartRaw {
            get {
                return ResourceManager.GetString("DspStartRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validáló induló népesség.
        /// </summary>
        public static string DspStartValidation {
            get {
                return ResourceManager.GetString("DspStartValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes induló népesség kisebbségekkel.
        /// </summary>
        public static string DspStartWithMinorities {
            get {
                return ResourceManager.GetString("DspStartWithMinorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes induló népesség kisebbségekkel és bevándorlókkal.
        /// </summary>
        public static string DspStartWithMinoritiesAndMigrants {
            get {
                return ResourceManager.GetString("DspStartWithMinoritiesAndMigrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szolgálati státusz.
        /// </summary>
        public static string DspWorkStatus {
            get {
                return ResourceManager.GetString("DspWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyers szolgálati státusz.
        /// </summary>
        public static string DspWorkStatusRaw {
            get {
                return ResourceManager.GetString("DspWorkStatusRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szolgálati státusz ideje.
        /// </summary>
        public static string DspWorkStatusTime {
            get {
                return ResourceManager.GetString("DspWorkStatusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induló népesség.
        /// </summary>
        public static string DsStartingPopulation {
            get {
                return ResourceManager.GetString("DsStartingPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettség.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legfeljebb 8 általános.
        /// </summary>
        public static string EducationED02 {
            get {
                return ResourceManager.GetString("EducationED02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Középfokú végzettség.
        /// </summary>
        public static string EducationED34 {
            get {
                return ResourceManager.GetString("EducationED34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felsőfokú végzettség.
        /// </summary>
        public static string EducationED58 {
            get {
                return ResourceManager.GetString("EducationED58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végzettség típus.
        /// </summary>
        public static string EducationType {
            get {
                return ResourceManager.GetString("EducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParaméterTáblák.
        /// </summary>
        public static string ExcelFilename {
            get {
                return ResourceManager.GetString("ExcelFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzó korévek az adathalmazban.
        /// </summary>
        public static string ExMissingAges {
            get {
                return ResourceManager.GetString("ExMissingAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExportDirectory {
            get {
                return ResourceManager.GetString("ExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nő.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nők.
        /// </summary>
        public static string Females {
            get {
                return ResourceManager.GetString("Females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megkísérlem újra generálni az adatokat.
        /// </summary>
        public static string GenerateForceAttempt {
            get {
                return ResourceManager.GetString("GenerateForceAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; adatgenerálása sikeresen megtörtént.
        /// </summary>
        public static string GenerateMessage {
            get {
                return ResourceManager.GetString("GenerateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibrid.
        /// </summary>
        public static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevándorló.
        /// </summary>
        public static string Immigrant {
            get {
                return ResourceManager.GetString("Immigrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jövedelme.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Életpálya jövedelem.
        /// </summary>
        public static string IncomeTotal {
            get {
                return ResourceManager.GetString("IncomeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Növekmény.
        /// </summary>
        public static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; betöltése.
        /// </summary>
        public static string LoadDataSourceMessage {
            get {
                return ResourceManager.GetString("LoadDataSourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; betöltése során hiba történt.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az elemek betöltése befejeződött.
        /// </summary>
        public static string LoadFinished {
            get {
                return ResourceManager.GetString("LoadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; beolvasása sikeresen megtörtént.
        /// </summary>
        public static string LoadMessage {
            get {
                return ResourceManager.GetString("LoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} db elem betöltése.
        /// </summary>
        public static string LoadStared {
            get {
                return ResourceManager.GetString("LoadStared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Többségi népesség.
        /// </summary>
        public static string Majority {
            get {
                return ResourceManager.GetString("Majority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Férfi.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Férfiak.
        /// </summary>
        public static string Males {
            get {
                return ResourceManager.GetString("Males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisebbség.
        /// </summary>
        public static string Minority {
            get {
                return ResourceManager.GetString("Minority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anya végzettsége.
        /// </summary>
        public static string MotherEducation {
            get {
                return ResourceManager.GetString("MotherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem értelmezhető.
        /// </summary>
        public static string NAP {
            get {
                return ResourceManager.GetString("NAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alap.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimista.
        /// </summary>
        public static string Optimistic {
            get {
                return ResourceManager.GetString("Optimistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyugdíj típus.
        /// </summary>
        public static string PensionType {
            get {
                return ResourceManager.GetString("PensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Százalék.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesszimista.
        /// </summary>
        public static string Pessimistic {
            get {
                return ResourceManager.GetString("Pessimistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Társadalmi csoport.
        /// </summary>
        public static string SocialGroup {
            get {
                return ResourceManager.GetString("SocialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Társadalmi csoportok.
        /// </summary>
        public static string SocialGroupsDataSource {
            get {
                return ResourceManager.GetString("SocialGroupsDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatforrások.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összesen.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érték.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Változó.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súly.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkavállalói státusz.
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes évet dolgozott.
        /// </summary>
        public static string WorkStatusA {
            get {
                return ResourceManager.GetString("WorkStatusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több, mint háromnegyed évet dolgozott.
        /// </summary>
        public static string WorkStatusB1 {
            get {
                return ResourceManager.GetString("WorkStatusB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több, mint fél évet dolgozott.
        /// </summary>
        public static string WorkStatusB2 {
            get {
                return ResourceManager.GetString("WorkStatusB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több, mint negyed évet dolgozott.
        /// </summary>
        public static string WorkStatusB3 {
            get {
                return ResourceManager.GetString("WorkStatusB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legfeljebb negyed évet dolgozott.
        /// </summary>
        public static string WorkStatusB4 {
            get {
                return ResourceManager.GetString("WorkStatusB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenlegi foglalkoztatási státusz.
        /// </summary>
        public static string WorkStatusCurrent {
            get {
                return ResourceManager.GetString("WorkStatusCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem dolgozott.
        /// </summary>
        public static string WorkStatusG {
            get {
                return ResourceManager.GetString("WorkStatusG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Következő foglalkoztatási státusz.
        /// </summary>
        public static string WorkStatusNext {
            get {
                return ResourceManager.GetString("WorkStatusNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkában töltött évek.
        /// </summary>
        public static string WorkYears {
            get {
                return ResourceManager.GetString("WorkYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Év.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
